POST localhost:8082/games
Content-Type: application/json

{
  "name": "Thibault"
}

###

GET localhost:8082/games

###

GET localhost:8082/games/4

###

POST localhost:8082/games/2
Content-Type: application/json

{
  "name": "Jean"
}

###

PATCH localhost:8082/games/1/start